DROP TABLE IF EXISTS BONDS;

CREATE TABLE BONDS
(
    SECID        VARCHAR(250) PRIMARY KEY,
    SHORTNAME    VARCHAR(30) NOT NULL,
    MATDATE      DATE,
    COUPONVALUE  DECIMAL     NOT NULL,
    COUPONPERIOD INT         NOT NULL,
    OFFERDATE    DATE,
    LOTVALUE     DECIMAL     NOT NULL
);